name: GitHub Actions Demo
run-name: ${{ github.actor}} is testing out GitHub Actions 
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
        - name: Run a one-line script number 1
          run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."

        - name : Run a one-line script number 2
          run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"

        - name: Run a one-line script number 3
          run: echo "ğŸš€ The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

        - name: Branch name and repository
          run: echo " The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
        - run: echo " The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
        - name: Check out repository code
          uses: actions/checkout@v4


        - run: echo "ğŸ›  The ${{ github.repository }} repository has been cloned to the runner."
        - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."

        - name: List files in the repository
          run: |
            ls ${{ github.workspace }}

        - run: echo "ğŸ This job's status is ${{ job.status }}."


          
